### ISSUE TITLE
paired fastq split by barcodes

### ISSUE THREAD

**Issue by summus-kong** [yodeng/fsplit#1]
can paired fastq file be splited by barcodes?

**Comment by yodeng** [comment]
Thanks for your question @summus-kong ,  I have updated this code and provided paired fastq support. That's all in version 1.0.6 and commit [457e1e84dca1821f1b50a732da9d195c6021567d](https://github.com/yodeng/fsplit/commit/457e1e84dca1821f1b50a732da9d195c6021567d).

Paired fastq (reads2 file)  can be passed by `-I/--Input` flag  and the barcode information file should be three columns like `sampleName barcodeSeq1 barcodeSeq2`. If only two columns given, the barcode2 sequence will be same as barcode1.  The arguments of reverse complement barcode sequence also be added. All usage and help can be show by command `fsplit split --help`.

**Comment by summus-kong** [comment]
Thank you four your kind reply. If it is convenient, I would like to know if you split the sequence and extract reads1 or how many bp of the first left end of reads2 sequence to split against barcode sequence?
Looking forward to your reply.






| |
Weibo Hou
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 2/1/2023 13:43 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [yodeng/fsplit] paired fastq split by barcodes (Issue #1) |

Thanks for your question @summus-kong , I have updated this code and provided paired fastq support. That's all in version 1.0.6 and commit 457e1e84dca1821f1b50a732da9d195c6021567d.

Paired fastq (reads2 file) can be passed by -I/--Input flag and the barcode information file should be three columns like sampleName barcodeSeq1 barcodeSeq2. If only two columns given, the barcode2 sequence will be same as barcode1. The arguments of reverse complement barcode sequence also be added. All usage and help can be show by command fsplit split --help.

**Comment by yodeng** [comment]
Hi, @summus-kong，
fsplit support paired fastq split  by paired barcode. Both barcodes search against left end of sequence, from the left 1st bp. 
Barcode1 search from read1 left end , barcode2 search from read2 left end at the same.  If all base matched (both allow default 
 0 base mismatch), the read1 and read2 will be written to output file named "samlesName.R1.fq" and "samlesName.R2.fq" respectively. Barcode sequence can be trimed in output reads file, this is optional by "--drup" flag.

**Comment by summus-kong** [comment]
Hi, yodeng,
Thank you for your reply. Do you start at the left end and search the whole reads for barcodes sequences?


| |
Weibo Hou
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 6/30/2023 11:16 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [yodeng/fsplit] paired fastq split by barcodes (Issue #1) |

Hi, @summus-kong，
fsplit support paired fastq split by paired barcode. Both barcodes search against left end of sequence, from the left 1st bp.
Barcode1 search from read1 left end , barcode2 search from read2 left end at the same. If all base matched (both allow default
0 base mismatch), the read1 and read2 will be written to output file named "samlesName.R1.fq" and "samlesName.R2.fq" respectively. Barcode sequence can be trimed in output reads file, this is optional by "--drup" flag.

**Comment by yodeng** [comment]
No, this only search the sequence from the left first bp to the length of barcode.

**Comment by summus-kong** [comment]
Thank you for your kind reply! 


| |
Weibo Hou
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 6/30/2023 11:30 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [yodeng/fsplit] paired fastq split by barcodes (Issue #1) |

No, this only search the sequence from the left first bp to the length of barcode.
